import 'package:flutter_test/flutter_test.dart';
import 'package:dosebuddy/core/records.dart';
import 'package:dosebuddy/core/store.dart';
import 'package:dosebuddy/core/reminders.dart';

Json prescription({String start='2026-09-01',String? end,List<int> times=const [480],String type='scheduled',num amount=1})=>{'name':'Example medication','strength':'10 mg','amount':amount,'unit':'tablet','type':type,'form':'Tablet','times':times,'start':start,'end':end,'active':true,'instructions':'As prescribed','food':'No preference','notes':'','reason':'','prescriber':'','pharmacy':''};

void main(){
  test('manual supply baseline prevents old corrections changing a fresh count',(){final r=Records(Records.empty());r.saveMedication('a',prescription(),DateTime(2026,9,1),supply:10);final d=r.schedule(DateTime(2026,9,2),DateTime(2026,9,2)).single;r.record(d,status:'Taken',now:DateTime(2026,9,2,9));r.saveMedication('a',prescription(),DateTime(2026,9,2,10),supply:20);r.record(d,status:'Taken',now:DateTime(2026,9,2,11),amount:2);expect(r.medications['a']['supply'],20);r.undo(d.key,DateTime(2026,9,2,12));expect(r.medications['a']['supply'],20);});

  test('course start and inclusive last day determine doses',(){final r=Records(Records.empty());r.saveMedication('a',prescription(start:'2026-09-10',end:'2026-09-12'),DateTime(2026,9,1));expect(r.schedule(DateTime(2026,9,1),DateTime(2026,9,15)).map((d)=>dayKey(d.at)),['2026-09-10','2026-09-11','2026-09-12']);});
  test('pause and resume preserve historical schedule versions',(){final r=Records(Records.empty());r.saveMedication('a',prescription(),DateTime(2026,9,1));r.changeActive('a',false,DateTime(2026,9,3,9));r.changeActive('a',true,DateTime(2026,9,5,9));expect(r.schedule(DateTime(2026,9,2),DateTime(2026,9,6)).map((d)=>dayKey(d.at)),['2026-09-02','2026-09-03','2026-09-06']);});
  test('editing today does not reinterpret earlier doses',(){final r=Records(Records.empty());r.saveMedication('a',prescription(),DateTime(2026,9,1));r.saveMedication('a',{...prescription(times:[600]),'strength':'20 mg'},DateTime(2026,9,3,9));final before=r.schedule(DateTime(2026,9,2),DateTime(2026,9,2));expect(before.single.details['strength'],'10 mg');expect(before.single.at.hour,8);expect(r.schedule(DateTime(2026,9,4),DateTime(2026,9,4)).single.at.hour,10);});
  test('duplicate record cannot double decrement stock; correction and undo reconcile',(){final r=Records(Records.empty());r.saveMedication('a',prescription(),DateTime(2026,9,1),supply:10);final d=r.schedule(DateTime(2026,9,2),DateTime(2026,9,2)).single;final now=DateTime(2026,9,2,9);r.record(d,status:'Taken',now:now);r.record(d,status:'Taken',now:now);expect(r.medications['a']['supply'],9);r.record(d,status:'Taken',now:now,amount:2.5);expect(r.medications['a']['supply'],7.5);r.undo(d.key,now);expect(r.medications['a']['supply'],10);expect(r.outcomes,isEmpty);});
  test('short supply correction restores only the actual deducted quantity',(){final r=Records(Records.empty());r.saveMedication('a',prescription(amount:2),DateTime(2026,9,1),supply:1);final d=r.schedule(DateTime(2026,9,2),DateTime(2026,9,2)).single;r.record(d,status:'Taken',now:DateTime(2026,9,2,9));r.undo(d.key,DateTime(2026,9,2,9));expect(r.medications['a']['supply'],1);});
  test('unrecorded scheduled doses stay in denominator and PRN is excluded',(){final r=Records(Records.empty());r.saveMedication('a',prescription(),DateTime(2026,9,1));final ds=r.schedule(DateTime(2026,9,1),DateTime(2026,9,10));r.record(ds.first,status:'Taken',now:DateTime(2026,9,10,12));r.record(ScheduledDose('prn_1','a',DateTime(2026,9,10),prescription()),status:'Taken',now:DateTime(2026,9,10,12),prn:true);final c=r.counts(DateTime(2026,9,1),DateTime(2026,9,10,12));expect(c,{'scheduled':10,'taken':1,'skipped':0,'unrecorded':9});});
  test('future actual times, invalid quantities, reversed dates and duplicate times are rejected',(){final r=Records(Records.empty());expect(()=>validateMedication(prescription(amount:0)),throwsArgumentError);expect(()=>validateMedication(prescription(amount:double.nan)),throwsArgumentError);expect(()=>validateMedication(prescription(start:'2026-09-12',end:'2026-09-10')),throwsArgumentError);expect(()=>validateMedication(prescription(times:[480,480])),throwsArgumentError);final d=ScheduledDose('k','a',DateTime(2026,9,1),prescription());expect(()=>r.record(d,status:'Taken',now:DateTime(2026,9,1),takenAt:DateTime(2026,9,2)),throwsArgumentError);});
  test('unrecorded is distinct from taken or skipped',(){final r=Records(Records.empty());final d=ScheduledDose('k','a',DateTime(2026,9,1,8),prescription());expect(r.status(d,DateTime(2026,9,1,7)),'Upcoming');expect(r.status(d,DateTime(2026,9,1,9)),'Not recorded');r.record(d,status:'Skipped',now:DateTime(2026,9,1,9),reason:'Clinician instruction');expect(r.status(d,DateTime(2026,9,1,9)),'Skipped');});
  test('reminder plan is bounded and excludes resolved or paused doses',(){final r=Records(Records.empty());r.saveMedication('a',prescription(times:[480,600,720,840]),DateTime(2026,9,1));final now=DateTime(2026,9,1);final p=ReminderPlan.create(r,now);expect(p.doses.length,60);r.record(p.doses.first,status:'Skipped',now:now);expect(ReminderPlan.create(r,now).doses.any((d)=>d.key==p.doses.first.key),false);r.changeActive('a',false,now);expect(ReminderPlan.create(r,now).doses,isEmpty);});
  test('civil-time dose identity is independent of timezone offsets',(){expect(doseKey('a',DateTime(2026,9,1),480),doseKey('a',DateTime.utc(2026,9,1),480));});
  test('failed persistence does not mutate visible records',()async{final store=AppStore(Records.empty(),(_)async=>throw StateError('Disk failure'));await expectLater(store.update((r)=>r.saveMedication('a',prescription(),DateTime(2026,9,1))),throwsStateError);expect(store.records.medications,isEmpty);expect(store.busy,false);});
  test('erase clears every health record and setting',()async{final data=Records.empty();data['symptoms']={'s':{'name':'test'}};data['audit']=[{'old':'value'}];data['emergency']={'allergies':'test'};data['settings']={'appLock':true};final store=AppStore(data,(_)async{});await store.erase();expect(store.data,Records.empty());});
}
