import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class CareCirclePage extends StatefulWidget { const CareCirclePage({super.key}); @override State<CareCirclePage> createState()=>_CareCirclePageState(); }
class _CareCirclePageState extends State<CareCirclePage>{
  List<Map<String,dynamic>> people=[];
  @override void initState(){super.initState();_load();}
  Future<void> _load()async{final p=await SharedPreferences.getInstance();final raw=p.getString('care_circle');if(raw!=null){people=(jsonDecode(raw) as List).map((e)=>Map<String,dynamic>.from(e)).toList();}if(mounted)setState((){});}
  Future<void> _save()async{final p=await SharedPreferences.getInstance();await p.setString('care_circle',jsonEncode(people));}
  Future<void> _add()async{final n=TextEditingController(),r=TextEditingController(text:'Family');bool schedule=true,adherence=true,symptoms=false,edit=false;final x=await showModalBottomSheet<Map<String,dynamic>>(context:context,isScrollControlled:true,builder:(ctx)=>StatefulBuilder(builder:(ctx,setLocal)=>Padding(padding:EdgeInsets.fromLTRB(24,24,24,MediaQuery.of(ctx).viewInsets.bottom+24),child:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Add to Care Circle',style:TextStyle(fontSize:25,fontWeight:FontWeight.w900)),const SizedBox(height:18),TextField(controller:n,decoration:const InputDecoration(labelText:'Name',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:r,decoration:const InputDecoration(labelText:'Relationship',border:OutlineInputBorder())),const SizedBox(height:18),const Text('Sharing permissions',style:TextStyle(fontWeight:FontWeight.w800)),SwitchListTile(contentPadding:EdgeInsets.zero,title:const Text('Medication schedule'),value:schedule,onChanged:(v)=>setLocal(()=>schedule=v)),SwitchListTile(contentPadding:EdgeInsets.zero,title:const Text('Adherence status'),value:adherence,onChanged:(v)=>setLocal(()=>adherence=v)),SwitchListTile(contentPadding:EdgeInsets.zero,title:const Text('Symptoms'),value:symptoms,onChanged:(v)=>setLocal(()=>symptoms=v)),SwitchListTile(contentPadding:EdgeInsets.zero,title:const Text('Can edit medications'),value:edit,onChanged:(v)=>setLocal(()=>edit=v)),const SizedBox(height:8),SizedBox(width:double.infinity,child:FilledButton(onPressed:()=>Navigator.pop(ctx,{'name':n.text.trim(),'relationship':r.text.trim(),'schedule':schedule,'adherence':adherence,'symptoms':symptoms,'edit':edit}),child:const Text('Add person')))])))));if(x!=null&&x['name'].toString().isNotEmpty){people.add(x);await _save();setState((){});}}
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Care Circle')),floatingActionButton:FloatingActionButton.extended(onPressed:_add,icon:const Icon(Icons.person_add_alt_1),label:const Text('Add person')),body:ListView(padding:const EdgeInsets.all(20),children:[Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:const Color(0xFFEEEFFF),borderRadius:BorderRadius.circular(20)),child:const Text('You control exactly what each person can see. Permissions can be changed or revoked at any time.',style:TextStyle(height:1.4))),const SizedBox(height:18),if(people.isEmpty)const Padding(padding:EdgeInsets.all(30),child:Column(children:[Icon(Icons.group_outlined,size:48,color:Colors.grey),SizedBox(height:12),Text('Your Care Circle is empty',style:TextStyle(fontSize:18,fontWeight:FontWeight.w800)),SizedBox(height:6),Text('Add a trusted person when you want help staying on top of your routine.',textAlign:TextAlign.center)])) else ...people.asMap().entries.map((e)=>Card(child:ListTile(contentPadding:const EdgeInsets.all(14),leading:CircleAvatar(child:Text(e.value['name'].toString()[0].toUpperCase())),title:Text(e.value['name'],style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${e.value['relationship']} • ${[if(e.value['schedule'])'schedule',if(e.value['adherence'])'adherence',if(e.value['symptoms'])'symptoms',if(e.value['edit'])'editing'].join(', ')}'),trailing:IconButton(icon:const Icon(Icons.delete_outline),onPressed:()async{people.removeAt(e.key);await _save();setState((){});}))))]));
}
