import 'package:flutter/material.dart';
import 'package:hive/hive.dart';
import 'package:intl/intl.dart';
import 'package:share_plus/share_plus.dart';
import 'models/medication.dart';
import 'models/dose_event.dart';
import 'models/symptom_event.dart';

class DoctorReportPage extends StatelessWidget{const DoctorReportPage({super.key});
  String report(){final now=DateTime.now(),start=now.subtract(const Duration(days:30));final meds=Hive.box<Medication>('medications').values.where((m)=>!m.isCompleted).toList();final doses=Hive.box<DoseEvent>('dose_events').values.where((d)=>d.scheduledAt.isAfter(start)&&!d.scheduledAt.isAfter(now)).toList();final symptoms=Hive.box<SymptomEvent>('symptom_events').values.where((s)=>s.occurredAt.isAfter(start)).toList();final taken=doses.where((d)=>['taken','late'].contains(d.status)).length;final adherence=doses.isEmpty?null:(taken/doses.length*100);final counts=<String,int>{};for(final s in symptoms){counts[s.name]=(counts[s.name]??0)+1;}return '''DoseBuddy Medication Summary\nGenerated ${DateFormat('MMMM d, yyyy').format(now)}\nPeriod: last 30 days\n\nADHERENCE\n${adherence==null?'Not enough logged dose history':'${adherence.toStringAsFixed(0)}% ($taken of ${doses.length} logged dose events taken)'}\n\nCURRENT MEDICATIONS\n${meds.isEmpty?'None listed':meds.map((m)=>'• ${m.name} ${m.dosage} • ${m.isAsNeeded?'as needed':'${m.times.length}× daily'}${m.reason.isEmpty?'':' • for ${m.reason}'}').join('\n')}\n\nREPORTED SYMPTOMS\n${counts.isEmpty?'None logged':counts.entries.map((e)=>'• ${e.key}: ${e.value} entr${e.value==1?'y':'ies'}').join('\n')}\n\nMISSED / SKIPPED\n${doses.where((d)=>['missed','skipped'].contains(d.status)).isEmpty?'None logged':doses.where((d)=>['missed','skipped'].contains(d.status)).map((d)=>'• ${DateFormat('MMM d, h:mm a').format(d.scheduledAt)} • ${d.status}${d.reason==null?'':' • ${d.reason}'}').join('\n')}\n\nThis summary reflects user-entered DoseBuddy records and is not a medical diagnosis.''';}
  @override Widget build(BuildContext context){final text=report();return Scaffold(backgroundColor:const Color(0xFFF6F7FB),appBar:AppBar(backgroundColor:const Color(0xFFF6F7FB),foregroundColor:const Color(0xFF191C2B),elevation:0,title:const Text('Doctor report',style:TextStyle(fontWeight:FontWeight.w800))),body:ListView(padding:const EdgeInsets.all(20),children:[Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(24)),child:SelectableText(text,style:const TextStyle(height:1.55,fontSize:14))),const SizedBox(height:18),FilledButton.icon(onPressed:()=>Share.share(text,subject:'DoseBuddy Medication Summary'),icon:const Icon(Icons.ios_share_rounded),label:const Text('Share report')),const SizedBox(height:10),const Text('Share this with your care team as a conversation aid. Verify medication details before relying on the report.',textAlign:TextAlign.center,style:TextStyle(fontSize:12,color:Color(0xFF8D93A6),height:1.4))]));}
}
