import 'package:flutter/material.dart';
import 'package:hive/hive.dart';
import 'package:intl/intl.dart';
import 'models/medication.dart';
import 'models/dose_event.dart';
import 'models/symptom_event.dart';
import 'symptom_logger_page.dart';
import 'doctor_report_page.dart';

class HealthTimelinePage extends StatefulWidget{const HealthTimelinePage({super.key});@override State<HealthTimelinePage> createState()=>_HealthTimelinePageState();}
class _Entry{final DateTime time;final bool symptom;final dynamic data;_Entry(this.time,this.symptom,this.data);}
class _HealthTimelinePageState extends State<HealthTimelinePage>{
  Medication? med(String id){for(final m in Hive.box<Medication>('medications').values){if(m.id==id)return m;}return null;}
  List<_Entry> entries(){final e=< _Entry>[];for(final d in Hive.box<DoseEvent>('dose_events').values){e.add(_Entry(d.takenAt??d.scheduledAt,false,d));}for(final s in Hive.box<SymptomEvent>('symptom_events').values){e.add(_Entry(s.occurredAt,true,s));}e.sort((a,b)=>b.time.compareTo(a.time));return e;}
  @override Widget build(BuildContext context){final all=entries();return Scaffold(backgroundColor:const Color(0xFFF6F7FB),appBar:AppBar(backgroundColor:const Color(0xFFF6F7FB),foregroundColor:const Color(0xFF191C2B),elevation:0,title:const Text('Health timeline',style:TextStyle(fontWeight:FontWeight.w800)),actions:[IconButton(tooltip:'Doctor report',icon:const Icon(Icons.description_outlined),onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const DoctorReportPage()))) ]),floatingActionButton:FloatingActionButton.extended(onPressed:()async{await Navigator.push(context,MaterialPageRoute(builder:(_)=>const SymptomLoggerPage()));setState((){});},icon:const Icon(Icons.add_reaction_outlined),label:const Text('Log symptom')),body:all.isEmpty?const Center(child:Padding(padding:EdgeInsets.all(30),child:Text('Your timeline will bring doses and symptoms together in one place.',textAlign:TextAlign.center,style:TextStyle(color:Color(0xFF7B8194),fontSize:16)))):ListView.builder(padding:const EdgeInsets.fromLTRB(20,12,20,100),itemCount:all.length,itemBuilder:(c,i){final x=all[i];final showDate=i==0||!DateUtils.isSameDay(all[i-1].time,x.time);return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[if(showDate)...[Padding(padding:const EdgeInsets.only(top:12,bottom:10),child:Text(DateFormat('EEEE, MMMM d').format(x.time),style:const TextStyle(fontWeight:FontWeight.w800,fontSize:18)))],x.symptom?_symptom(x.data):_dose(x.data)]); }));}
  Widget _dose(DoseEvent d){final m=med(d.medicationId);final good=['taken','late'].contains(d.status);return card(icon:good?Icons.check_rounded:Icons.medication_outlined,iconBg:good?const Color(0xFFEAF7EF):const Color(0xFFF0F1FC),iconColor:good?const Color(0xFF2E8B57):const Color(0xFF5965D8),title:m?.name??'Medication',subtitle:'${DateFormat('h:mm a').format(d.scheduledAt)} • ${m?.dosage??''}',trailing:d.status.toUpperCase(),detail:d.reason==null?null:'Reason: ${d.reason}');}
  Widget _symptom(SymptomEvent s){final m=s.medicationId==null?null:med(s.medicationId!);return card(icon:Icons.monitor_heart_outlined,iconBg:const Color(0xFFFFF0ED),iconColor:const Color(0xFFD56A52),title:s.name,subtitle:'${DateFormat('h:mm a').format(s.occurredAt)} • Severity ${s.severity}/5',trailing:s.durationMinutes==null?'SYMPTOM':'${s.durationMinutes} MIN',detail:[if(m!=null)'Linked by you to ${m.name}',if(s.notes!=null)s.notes!].join(' • '));}
  Widget card({required IconData icon,required Color iconBg,required Color iconColor,required String title,required String subtitle,required String trailing,String? detail})=>Container(margin:const EdgeInsets.only(bottom:10),padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20)),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Container(width:46,height:46,decoration:BoxDecoration(color:iconBg,borderRadius:BorderRadius.circular(14)),child:Icon(icon,color:iconColor)),const SizedBox(width:13),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontWeight:FontWeight.w700,fontSize:16)),Text(subtitle,style:const TextStyle(color:Color(0xFF7B8194),fontSize:13)),if(detail!=null&&detail.isNotEmpty)...[const SizedBox(height:5),Text(detail,style:const TextStyle(color:Color(0xFF656B7D),fontSize:12))]])),Text(trailing,style:const TextStyle(fontSize:10,fontWeight:FontWeight.w800,color:Color(0xFF7B8194)))]));
}
