import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'models/medication.dart';
import 'services/notification_services.dart';
import 'splash_screen.dart';
import 'widgets/dosebuddy_theme.dart';
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:flutter/foundation.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Requires platform configuration generated by `flutterfire configure`.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  await FirebaseAppCheck.instance.activate(
    androidProvider: kDebugMode ? AndroidProvider.debug : AndroidProvider.playIntegrity,
    appleProvider: kDebugMode ? AppleProvider.debug : AppleProvider.deviceCheck,
  );

  //Initialize Hive
  await Hive.initFlutter();
  Hive.registerAdapter(MedicationAdapter());
  await Hive.openBox<Medication>('medications');

  //Initialize notifications
  await NotificationService().initialize();

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'DoseBuddy',
      debugShowCheckedModeBanner: false,
      theme: DoseBuddyTheme.light,
      home: const SplashScreen(),
    );
  }
}
