import 'package:flutter/material.dart';
import 'package:hive/hive.dart';
import 'models/medication.dart';
import 'add_medication_page.dart';
import 'routine_tools_page.dart';
import 'prn_log_page.dart';
import 'prescription_capture_page.dart';
import 'drug_safety_page.dart';

class MedicationsPage extends StatefulWidget { const MedicationsPage({super.key}); @override State<MedicationsPage> createState()=>_MedicationsPageState(); }
class _MedicationsPageState extends State<MedicationsPage>{
  static const purple=Color(0xFF5B67CA); String filter='Active'; List<Medication> meds=[];
  @override void initState(){super.initState();load();} void load(){meds=Hive.box<Medication>('medications').values.toList(); if(mounted)setState((){});}
  List<Medication> get shown=>meds.where((m){if(filter=='As needed')return m.isAsNeeded&&!m.isCompleted;if(filter=='Completed')return m.isCompleted;return !m.isCompleted&&m.lifecycleStatus=='active'&&!m.isAsNeeded;}).toList();
  Future<void> add()async{final r=await Navigator.push(context,MaterialPageRoute(builder:(_)=>const AddMedicationPage()));if(r==true)load();}
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFFF7F8FC),body:SafeArea(child:RefreshIndicator(onRefresh:()async=>load(),child:ListView(padding:const EdgeInsets.fromLTRB(24,24,24,110),children:[
    Row(children:[const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Medications',style:TextStyle(fontSize:34,fontWeight:FontWeight.w900)),SizedBox(height:4),Text('Your complete medication routine',style:TextStyle(color:Color(0xFF858BA0),fontSize:15))])),IconButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const RoutineToolsPage())),icon:const Icon(Icons.tune_rounded),tooltip:'Routine tools'),IconButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const PrescriptionCapturePage())),icon:const Icon(Icons.document_scanner_outlined),tooltip:'Add from prescription'),IconButton.filled(style:IconButton.styleFrom(backgroundColor:const Color(0xFFE8EAFF),foregroundColor:purple),onPressed:add,icon:const Icon(Icons.add))]),const SizedBox(height:24),
    SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:['Active','As needed','Completed'].map((f)=>Padding(padding:const EdgeInsets.only(right:8),child:ChoiceChip(label:Text(f),selected:filter==f,onSelected:(_)=>setState(()=>filter=f),selectedColor:const Color(0xFFE4E7FF),side:BorderSide.none))).toList())),const SizedBox(height:22),
    if(shown.isEmpty)_empty() else ...shown.map(card),
  ]))),floatingActionButton:FloatingActionButton.extended(onPressed:add,backgroundColor:purple,foregroundColor:Colors.white,icon:const Icon(Icons.add),label:const Text('Add medication',style:TextStyle(fontWeight:FontWeight.w700))));
  Widget _empty()=>Container(padding:const EdgeInsets.all(30),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(24)),child:Column(children:[const Icon(Icons.medication_outlined,size:48,color:Color(0xFF9AA0B4)),const SizedBox(height:14),Text(filter=='Active'?'No active medications yet':'Nothing here yet',style:const TextStyle(fontSize:19,fontWeight:FontWeight.w800)),const SizedBox(height:6),const Text('Add a medication and DoseBuddy will organize the routine for you.',textAlign:TextAlign.center,style:TextStyle(color:Color(0xFF858BA0))) ]));
  Widget card(Medication m){final days=m.daysUntilOut(); final course=m.courseDaysRemaining; return GestureDetector(onTap:()=>details(m),child:Container(margin:const EdgeInsets.only(bottom:14),padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(22),boxShadow:[BoxShadow(color:Colors.black.withAlpha(8),blurRadius:16,offset:const Offset(0,5))]),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Container(width:52,height:52,decoration:BoxDecoration(color:const Color(0xFFE9F7EF),borderRadius:BorderRadius.circular(16)),child:const Icon(Icons.medication_rounded,color:Color(0xFF35A66F))),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(m.name,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w800)),const SizedBox(height:3),Text('${m.dosage} • ${m.dosageForm}',style:const TextStyle(color:Color(0xFF858BA0)))])),const Icon(Icons.chevron_right,color:Color(0xFFB0B4C2))]),const SizedBox(height:16),Wrap(spacing:8,runSpacing:8,children:[_tag(m.isAsNeeded?'As needed':'${m.times.length}× daily',Icons.schedule),if(m.foodInstruction!='No preference')_tag(m.foodInstruction,Icons.restaurant_outlined),if(course!=null)_tag('$course days left',Icons.calendar_today_outlined),if(days!=null)_tag('$days supply days',Icons.inventory_2_outlined)]),if(m.reason.isNotEmpty)...[const SizedBox(height:14),Text('For ${m.reason}',style:const TextStyle(fontWeight:FontWeight.w600,color:Color(0xFF555B70)))],if(m.needsRefill())...[const SizedBox(height:14),Container(padding:const EdgeInsets.all(11),decoration:BoxDecoration(color:const Color(0xFFFFF4DE),borderRadius:BorderRadius.circular(12)),child:const Row(children:[Icon(Icons.warning_amber_rounded,size:19,color:Color(0xFFB7791F)),SizedBox(width:8),Text('Running low • plan your refill',style:TextStyle(fontWeight:FontWeight.w700,color:Color(0xFF8A5A16))) ]))]])));
  }
  Widget _tag(String s,IconData i)=>Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:7),decoration:BoxDecoration(color:const Color(0xFFF2F3F8),borderRadius:BorderRadius.circular(20)),child:Row(mainAxisSize:MainAxisSize.min,children:[Icon(i,size:15,color:const Color(0xFF6F7588)),const SizedBox(width:5),Text(s,style:const TextStyle(fontSize:12,fontWeight:FontWeight.w600,color:Color(0xFF62687B)))]));
  void details(Medication m)=>showModalBottomSheet(context:context,isScrollControlled:true,backgroundColor:Colors.transparent,builder:(_)=>DraggableScrollableSheet(initialChildSize:.72,maxChildSize:.92,minChildSize:.45,builder:(c,sc)=>Container(padding:const EdgeInsets.fromLTRB(24,12,24,30),decoration:const BoxDecoration(color:Colors.white,borderRadius:BorderRadius.vertical(top:Radius.circular(30))),child:ListView(controller:sc,children:[Center(child:Container(width:44,height:5,decoration:BoxDecoration(color:Colors.grey.shade300,borderRadius:BorderRadius.circular(3)))),const SizedBox(height:24),Text(m.name,style:const TextStyle(fontSize:28,fontWeight:FontWeight.w900)),Text('${m.dosage} • ${m.dosageForm}',style:const TextStyle(color:Color(0xFF858BA0),fontSize:16)),const SizedBox(height:24),_row('Schedule',m.isAsNeeded?'Take as needed':m.times.join(' • ')),_row('Dose','${m.pillsPerDose} ${m.dosageForm.toLowerCase()}${m.pillsPerDose==1?'':'s'}'),if(m.foodInstruction!='No preference')_row('Food',m.foodInstruction),if(m.reason.isNotEmpty)_row('Taking for',m.reason),if(m.instructions.isNotEmpty)_row('Directions',m.instructions),if(m.pillsRemaining!=null)_row('Supply','${m.pillsRemaining} remaining${m.daysUntilOut()!=null?' • ~${m.daysUntilOut()} days':''}'),if(m.prescriber.isNotEmpty)_row('Prescriber',m.prescriber),if(m.pharmacy.isNotEmpty)_row('Pharmacy',m.pharmacy),if(m.notes.isNotEmpty)_row('Notes',m.notes),const SizedBox(height:18),Wrap(spacing:10,runSpacing:10,children:[if(m.isAsNeeded)FilledButton.icon(onPressed:()async{await Navigator.push(context,MaterialPageRoute(builder:(_)=>PrnLogPage(medication:m)));if(context.mounted)Navigator.pop(context);load();},icon:const Icon(Icons.bolt_rounded),label:const Text('Log dose')),if(m.pillsRemaining!=null)OutlinedButton.icon(onPressed:()=>_refill(m),icon:const Icon(Icons.inventory_2_outlined),label:const Text('Refill supply')),OutlinedButton.icon(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>DrugSafetyPage(medication:m))),icon:const Icon(Icons.health_and_safety_outlined),label:const Text('Safety info')),OutlinedButton.icon(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const RoutineToolsPage())),icon:const Icon(Icons.tune_rounded),label:const Text('Routine settings'))])]))));

  Future<void> _refill(Medication m) async {final c=TextEditingController(text:m.totalPills?.toString()??'');final value=await showDialog<int>(context:context,builder:(ctx)=>AlertDialog(title:Text('Refill ${m.name}'),content:TextField(controller:c,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'New quantity')),actions:[TextButton(onPressed:()=>Navigator.pop(ctx),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(ctx,int.tryParse(c.text)),child:const Text('Save'))]));c.dispose();if(value!=null&&value>0){m.refill(value);await m.save();load();if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('${m.name} supply updated to $value')));}}
  Widget _row(String a,String b)=>Padding(padding:const EdgeInsets.symmetric(vertical:11),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[SizedBox(width:105,child:Text(a,style:const TextStyle(color:Color(0xFF8B90A3),fontWeight:FontWeight.w600))),Expanded(child:Text(b,style:const TextStyle(fontWeight:FontWeight.w700,height:1.35)))]));
}
