import 'package:flutter/material.dart';
import 'package:hive/hive.dart';
import 'models/medication.dart';
import 'models/dose_event.dart';

class PrnLogPage extends StatefulWidget {final Medication medication;const PrnLogPage({super.key,required this.medication});@override State<PrnLogPage> createState()=>_PrnLogPageState();}
class _PrnLogPageState extends State<PrnLogPage>{final reason=TextEditingController(),notes=TextEditingController();int amount=1;static const purple=Color(0xFF5B67CA);
@override void dispose(){reason.dispose();notes.dispose();super.dispose();}
Future<void> save() async {final now=DateTime.now();final e=DoseEvent(id:'prn_${widget.medication.id}_${now.millisecondsSinceEpoch}',medicationId:widget.medication.id,scheduledAt:now,takenAt:now,status:'taken',amount:amount,reason:reason.text.trim().isEmpty?null:reason.text.trim(),notes:notes.text.trim().isEmpty?null:notes.text.trim());await Hive.box<DoseEvent>('dose_events').put(e.id,e);if(widget.medication.pillsRemaining!=null){widget.medication.pillsRemaining=(widget.medication.pillsRemaining!-amount).clamp(0,999999);await widget.medication.save();}if(mounted)Navigator.pop(context,true);}
@override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFFF7F8FC),appBar:AppBar(backgroundColor:const Color(0xFFF7F8FC),foregroundColor:Colors.black,surfaceTintColor:Colors.transparent,title:const Text('Log as-needed dose',style:TextStyle(fontWeight:FontWeight.w800))),body:ListView(padding:const EdgeInsets.all(20),children:[Text(widget.medication.name,style:const TextStyle(fontSize:28,fontWeight:FontWeight.w900)),Text('${widget.medication.dosage} • ${widget.medication.dosageForm}',style:const TextStyle(color:Color(0xFF8B93AA))),const SizedBox(height:24),const Text('Why are you taking it?',style:TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:8),TextField(controller:reason,decoration:_d('e.g. headache, allergy symptoms, pain')),const SizedBox(height:18),Row(children:[const Text('Units taken',style:TextStyle(fontWeight:FontWeight.w800)),const Spacer(),IconButton(onPressed:amount>1?()=>setState(()=>amount--):null,icon:const Icon(Icons.remove_circle_outline)),Text('$amount',style:const TextStyle(fontSize:18,fontWeight:FontWeight.w800)),IconButton(onPressed:()=>setState(()=>amount++),icon:const Icon(Icons.add_circle_outline))]),const SizedBox(height:18),const Text('Notes',style:TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:8),TextField(controller:notes,maxLines:3,decoration:_d('Optional context')),const SizedBox(height:26),SizedBox(height:54,child:FilledButton(style:FilledButton.styleFrom(backgroundColor:purple),onPressed:save,child:const Text('Log dose',style:TextStyle(fontWeight:FontWeight.w800))))]));
InputDecoration _d(String h)=>InputDecoration(hintText:h,filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(16),borderSide:BorderSide.none));}
