import 'package:flutter/material.dart';
import 'package:hive/hive.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'models/medication.dart';

class RoutineToolsPage extends StatefulWidget {
  const RoutineToolsPage({super.key});
  @override State<RoutineToolsPage> createState()=>_RoutineToolsPageState();
}
class _RoutineToolsPageState extends State<RoutineToolsPage>{
  bool followUp=true, refill=true; int followUpMinutes=15; bool travel=false; String travelZone='Keep current schedule';
  static const purple=Color(0xFF5B67CA);
  @override void initState(){super.initState();_load();}
  Future<void> _load() async {final p=await SharedPreferences.getInstance();setState((){followUp=p.getBool('smart_followup')??true;refill=p.getBool('refill_alerts')??true;followUpMinutes=p.getInt('followup_minutes')??15;travel=p.getBool('travel_mode')??false;travelZone=p.getString('travel_behavior')??'Keep current schedule';});}
  Future<void> _save() async {final p=await SharedPreferences.getInstance();await p.setBool('smart_followup',followUp);await p.setBool('refill_alerts',refill);await p.setInt('followup_minutes',followUpMinutes);await p.setBool('travel_mode',travel);await p.setString('travel_behavior',travelZone);if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Routine settings saved')));}
  @override Widget build(BuildContext context){final meds=Hive.box<Medication>('medications').values.where((m)=>!m.isCompleted).toList();return Scaffold(backgroundColor:const Color(0xFFF7F8FC),appBar:AppBar(backgroundColor:const Color(0xFFF7F8FC),foregroundColor:Colors.black,surfaceTintColor:Colors.transparent,title:const Text('Routine tools',style:TextStyle(fontWeight:FontWeight.w800))),body:ListView(padding:const EdgeInsets.fromLTRB(20,8,20,40),children:[
    _card('Smart reminders',Icons.notifications_active_outlined,[SwitchListTile(contentPadding:EdgeInsets.zero,title:const Text('Follow-up reminders',style:TextStyle(fontWeight:FontWeight.w700)),subtitle:Text('Remind me again if a dose is still unresolved after $followUpMinutes minutes'),value:followUp,onChanged:(v)=>setState(()=>followUp=v)),if(followUp)Slider(value:followUpMinutes.toDouble(),min:5,max:60,divisions:11,label:'$followUpMinutes min',onChanged:(v)=>setState(()=>followUpMinutes=v.round())),SwitchListTile(contentPadding:EdgeInsets.zero,title:const Text('Refill alerts',style:TextStyle(fontWeight:FontWeight.w700)),subtitle:const Text('Surface medications before their supply runs low'),value:refill,onChanged:(v)=>setState(()=>refill=v))]),
    _card('Your routines',Icons.view_timeline_outlined,[..._routine('Morning',meds.where((m)=>m.times.any((t)=>_hour(t)<12)).toList()),..._routine('Afternoon',meds.where((m)=>m.times.any((t){final h=_hour(t);return h>=12&&h<17;})).toList()),..._routine('Evening',meds.where((m)=>m.times.any((t)=>_hour(t)>=17)).toList())]),
    _card('Travel mode',Icons.flight_takeoff_outlined,[SwitchListTile(contentPadding:EdgeInsets.zero,title:const Text('Travel mode',style:TextStyle(fontWeight:FontWeight.w700)),subtitle:const Text('Keep your routine understandable when your timezone changes'),value:travel,onChanged:(v)=>setState(()=>travel=v)),if(travel)...['Keep current schedule','Keep home-time schedule'].map((e)=>RadioListTile<String>(contentPadding:EdgeInsets.zero,title:Text(e),subtitle:Text(e=='Keep current schedule'?'Use the same clock times at your destination.':'Keep doses anchored to your home timezone.'),value:e,groupValue:travelZone,onChanged:(v)=>setState(()=>travelZone=v!))),if(travel)Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:const Color(0xFFFFF4DE),borderRadius:BorderRadius.circular(14)),child:const Text('For medicines where timing changes may matter, confirm your travel plan with your pharmacist or clinician.',style:TextStyle(fontSize:12.5,height:1.35,color:Color(0xFF7A581B))))]),
    const SizedBox(height:8),SizedBox(height:54,child:FilledButton(style:FilledButton.styleFrom(backgroundColor:purple),onPressed:_save,child:const Text('Save routine settings',style:TextStyle(fontWeight:FontWeight.w800))))
  ]));}
  Widget _card(String title,IconData icon,List<Widget> children)=>Container(margin:const EdgeInsets.only(bottom:16),padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(22)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Icon(icon,color:purple),const SizedBox(width:9),Text(title,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w800))]),const SizedBox(height:10),...children]));
  List<Widget> _routine(String title,List<Medication> meds)=>[const SizedBox(height:10),Text(title.toUpperCase(),style:const TextStyle(fontSize:11,fontWeight:FontWeight.w800,color:Color(0xFF8B93AA),letterSpacing:1)),const SizedBox(height:6),if(meds.isEmpty)const Text('No medications',style:TextStyle(color:Color(0xFF9AA0B4))) else ...meds.map((m)=>Padding(padding:const EdgeInsets.symmetric(vertical:5),child:Row(children:[const Icon(Icons.medication_rounded,size:18,color:purple),const SizedBox(width:8),Expanded(child:Text(m.name,style:const TextStyle(fontWeight:FontWeight.w600))),Text(m.times.where((t)=>title=='Morning'?_hour(t)<12:title=='Afternoon'?(_hour(t)>=12&&_hour(t)<17):_hour(t)>=17).join(', '),style:const TextStyle(fontSize:12,color:Color(0xFF8B93AA)))])))];
  int _hour(String t){final p=t.split(' ');final hm=p[0].split(':');int h=int.parse(hm[0]);if(p.length>1&&p[1]=='PM'&&h!=12)h+=12;if(p.length>1&&p[1]=='AM'&&h==12)h=0;return h;}
}
